swagger: "2.0"
info:
  title: example Service
  version: ""
host: localhost:9000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /family:
    get:
      tags:
      - exmp
      summary: get-fam exmp
      operationId: exmp#get-fam
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ExmpGetFamResponseBody'
      schemes:
      - http
  /person:
    get:
      tags:
      - exmp
      summary: get-person exmp
      operationId: exmp#get-person
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ExmpGetPersonResponseBody'
      schemes:
      - http
definitions:
  ExmpGetFamResponseBody:
    title: 'Mediatype identifier: application/family; view=default'
    type: object
    properties:
      father:
        $ref: '#/definitions/PersonResponseBody'
      kids:
        type: array
        items:
          $ref: '#/definitions/PersonResponseBody'
        example:
        - age: 474348598118457068
          name: Quisquam est cum quia.
        - age: 474348598118457068
          name: Quisquam est cum quia.
        - age: 474348598118457068
          name: Quisquam est cum quia.
      mother:
        $ref: '#/definitions/PersonResponseBody'
      size:
        type: integer
        example: 6488358795573559614
        format: int64
      surname:
        type: string
        example: Saepe similique.
    description: Get-FamResponseBody result type (default view)
    example:
      father:
        age: 474348598118457068
        name: Quisquam est cum quia.
      kids:
      - age: 474348598118457068
        name: Quisquam est cum quia.
      - age: 474348598118457068
        name: Quisquam est cum quia.
      - age: 474348598118457068
        name: Quisquam est cum quia.
      - age: 474348598118457068
        name: Quisquam est cum quia.
      mother:
        age: 474348598118457068
        name: Quisquam est cum quia.
      size: 5828639532779704420
      surname: Quasi ex quasi dolore facere.
  ExmpGetPersonResponseBody:
    title: 'Mediatype identifier: application/person; view=default'
    type: object
    properties:
      age:
        type: integer
        example: 88636338797837949
        format: int64
      name:
        type: string
        example: Perferendis accusamus soluta eum et reiciendis quisquam.
    description: Get-PersonResponseBody result type (default view)
    example:
      age: 7702877539141549513
      name: Consequatur fuga quia distinctio ipsa corporis.
  PersonResponseBody:
    title: 'Mediatype identifier: application/person; view=default'
    type: object
    properties:
      age:
        type: integer
        example: 1093022047049393514
        format: int64
      name:
        type: string
        example: Culpa sit eos ut ipsa consequatur rerum.
    example:
      age: 2570375494750437289
      name: Praesentium possimus ut aut consequatur repellendus et.
